
@url = http://192.168.0.15:8900
# @name login
POST {{url}}/api
Authorization: Basic delight:elwasys2014

{
    "devicetype": "tester"
}

###
@token = {{login.response.body.0.success.username}}
#
GET {{url}}/api/{{token}}/config

###

GET {{url}}/api/{{token}}/lights/1

###

GET {{url}}/api/{{token}}/sensors