name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Apply version number
      run: sed -iE "s/0.0.0-local-development/${{ github.event.release.tag_name }}/g" Common/pom.xml Client-Raspi/pom.xml Common/src/main/java/org/kabieror/elwasys/common/Utilities.java

    - name: Build Common
      run: mvn install
      working-directory: Common

    - name: Build Raspi-Client
      run: mvn install
      working-directory: Client-Raspi

    - name: Publish runnable JAR
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: Client-Raspi/target/raspi-client-${{ github.event.release.tag_name }}-jar-with-dependencies.jar
        asset_name: raspi-client-${{ github.event.release.tag_name }}.jar
        tag: ${{ github.event.release.tag_name }}
        overwrite: true
