# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'liberica'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Regex Replace
      uses: ashley-taylor/regex-property-action@v1.4
      with:
        # The string to apply replace to
        value: 
        # The text of the regex pattern
        regex: 
        # Flags for the regex
        flags: # optional, default is g
        # String that replaces the substring specified by the regex
        replacement: # default is $1

    - name: Apply version number
      run: sed -iE "s/0.0.0-local-development/${{ github.event.release.tag_name }}/g" Common/pom.xml Client-Raspi/pom.xml Common/src/main/java/org/kabieror/elwasys/common/Utilities.java

    - name: Build Common
      run: mvn install
      working-directory: Common

    - name: Build Raspi-Client
      run: mvn install
      working-directory: Client-Raspi

    - name: Publish runnable JAR
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ github.token }}
        file: Client-Raspi/target/raspi-client-${{ github.event.release.tag_name }}-jar-with-dependencies.jar
        asset_name: raspi-client-${{ github.event.release.tag_name }}.jar
        tag: ${{ github.ref }}
        overwrite: true
        body: "elwaSys client for Raspberry Pi"
